baseURL = "http://localhost:8080"
title = "HUGO.386"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "HUGO.386"
preserveTaxonomyNames = true
paginate = 3

[params]
    # The name to display as main title in the home page
    mainpagetitle = "HUGO.386"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the early 90s!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "This theme is the Hugo port of the BOOTSTRA.386 theme for a cool retro look on your blog. Check the links below to access the posts."

    # The name to display in the copyright section in the footer
    copyrightname = "JM Fergeau"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "http://jmf-portfolio.netlify.com"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = true

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "JM Fergeau"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "http://jmf-portfolio.netlify.com"

    # Text to go before copyright information
    prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "Example site"

[taxonomies]
category = "categories"
tag = "tags"
authors = "authors"
