base_url = "http://localhost:8080"
# theme = "zola.386"

default_language = "en"
title = "ZOLA.386"
description = "A port of the BOOTSTRA.386 theme."

generate_feed = true
generate_rss = true

taxonomies = [
  {name="categories", rss=true},
  {name="tags", rss=true},
  {name="authors", rss=true},
]

compile_sass = false
build_search_index = false

[markdown]
highlight_code = true

[extra]
author = "José Lopes"
year = "2020"

keywords = "zola, theme, retro, hacking"
theme_color = "#000084"
